config/routes.rb
Rails.application.routes.draw do

  # get 'dashboards/show'
  get "/dashboard", to: 'dashboards#show'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # get 'mood', to: 'pages#moodselector'
  # get "/dashboard", to: 'dashboards#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues, only: [:index, :new, :create, :show] do
    resources :favorites, only: :create
    resources :spots, only: :create
    resources :bookings, only: :create
    resources :reviews, only: :create
  end
  resources :favorites, only: [:destroy]
  resources :favorites, except: [:new, :create]

  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :venue
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  validates :hotness_level, presence: true
end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
  has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :favorites, dependent: :destroy
  has_many :venues, through: :favorites
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :unicorn
  before_create :add_first_unicorn_to_user

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def earn_point
    self.point += 1
    self.unicorn = Unicorn.where("levelup_point <= ?", self.point).last
    self.save
  end

  private

  def add_first_unicorn_to_user
    self.unicorn = Unicorn.first
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_attachment :photo
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :venue_categories, dependent: :destroy
  has_many :categories, through: :venue_categories
  has_many :spots, dependent: :destroy
  has_many :bookings, through: :spots

  CATEGORIES = ["Bar", "Restaurant", "Cafe"]
  MOODS = ['fun', 'chill', 'seductive', 'adventurous', 'classy',]
  AREAS = ["Chelsea", "Shoreditch", "Soho", "Knightsbridge", "Mayfair", "Marylebone", "Hampstead", "Kensington"]
  validates :area, presence: true

  def favorite?(user)
    user.venues.include? self
    #user.venues.include? @venue <- you're trying to access @venue so using self.
  end


  private
  def area_in_london
    self.areas + ', London, UK'
  end
end

app/models/venue_category.rb
class VenueCategory < ApplicationRecord
  belongs_to :venue
  belongs_to :category
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    #@booking.spot =
    if @booking.save
      redirect_to dashboard_path
    else
      #render
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :moodselector ]

  def home
  end

  def moodselector
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @venue = Venue.find(params[:venue_id])
    @spot = Spot.new(spot_params)
    @spot.venue = @venue
    @spot.save
    authorize @spot
    current_user.earn_point
    flash[:notice] = "🦄 You have earned 1 point 🦄"
    redirect_to venue_path(@venue)
  end

  private

  def spot_params
    params.require(:spot).permit(:photo, :name)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @venues = policy_scope(Venue)
    @venues = Venue.all
    @venues = @venues.where(area: params[:area]) if !params[:area].blank?
    @venues = @venues.where(mood: params[:mood]) if !params[:mood].blank?
    # @venues = @venue.near('Shoreditch', 10)

    # @venues = @venues.where(category: params[:category]) if !params[:category].blank?

    cat_array = []
    cat_array << 'restaurant' if params['restaurant'] == 'on'
    cat_array << 'bar' if params['bar'] == 'on'
    cat_array << 'cafe' if params['cafe'] == 'on'

    # @venues = @venues.where(category: cat_array) if cat_array.any?

    @venues = @venues.joins(:categories).where(categories: {title: cat_array}) if cat_array.any?

    @venues = @venues.uniq

    session[:area] = params[:area]
    session[:categories] = cat_array

    @hash = Gmaps4rails.build_markers(@venues) do |venue, marker|
      marker.lat venue.latitude
      marker.lng venue.longitude
      marker.picture({
                  url: view_context.image_path('unicorn-index.png'),
                  width: 45,
                  height: 75
                 })
      marker.infowindow render_to_string(partial: "/venues/map_box", locals: { venue: venue })
      marker.json({ id: venue.id })
    end

    # @favorite = Favorite.new
    # @is_favorite = current_user.venues.include? @venue

  end


  def show
    @hash = Gmaps4rails.build_markers(@venue) do |venue, marker|
      marker.lat venue.latitude
      marker.lng venue.longitude
      marker.picture({
          url: view_context.image_path('unicorn-icon.svg'),
          width: 50,
          height: 50
          })
    end

    @spot = Spot.new

    @favorite = Favorite.new

    @booking = Booking.new

    @review = Review.new

    if user_signed_in?
    @is_favorite = @venue.favorite?(current_user)

    end
    #checking if current user's favorite venues array includes the venue he's visiting now(@venue)

  end

  def new
    @venue = Venue.new
    authorize @venue
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to venues_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @venue.update(venue_params)
      redirect_to venues_path
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_path
  end


  private

  def set_venue
    @venue = Venue.find(params[:id])
    authorize @venue
  end

  def venue_params
    params.require(:venue).permit(:name, :address, :area, :category, :mood, :description, :price, :light_level, :noise_level, :couch_comfort, :staff_level, :unicorn_score, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shiny Unicorn</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta charset="utf-8"></meta>

    <!-- Google result text-->
    <title>Find Magical Date Spots in London</title>
    <!-- Google result description-->
    <meta name="description" content="Shiny Unicorn">
    <meta property="og:title" content="Shiny Unicorn helps you find the best places to go on dates.">
    <meta property="og:image" content="facebook-card.jpg">
    <meta property="og:description" content="Shiny Unicorn is the best way to find the perfect date spots. Discover magical date spots in your area.">
    <meta property="og:site_name" content="Shiny Unicorn"/>

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@ShinyUnicornLdn">
    <meta name="twitter:title" content="Shiny Unicorn helps you find the best places to go on dates.">
    <meta name="twitter:description" content="Shiny Unicorn is the best way to find the perfect date spots. Discover magical date spots in your area.">
    <meta name="twitter:creator" content="@ShinyUnicornLdn">
    <meta name="twitter:image:src" content="http://twitter-card.jpg">

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <% if params[:action] == "home" %>
    <% variable = "second-class-that-we-want-to-add" %>
  <% else %>
    <% variable = "class-that-we-want-to-add" %>
  <% end %>
  <body class="<%= variable %>">
  <%= render 'shared/navbar' %>
  <% render 'shared/sidebar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%# render 'shared/footer' %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:after_js) %>
  <%= cloudinary_js_config %>
</body>

</html>

app/views/pages/home.html.erb
<% content_for(:navbar_class, "unicorn-navbar-home") %>



<div class="banner-home">
  <div class="banner-content">
    <h1 class="title">
      <span class="shiny-unicorn">Hi, I'm Shiny Unicorn.</span>
      <br>Let me find
      <span class="magical">Magical date spots</span>
      for you!
    </h1>
    <form action="<%= venues_path %>" class="form-inline">
      <div class="search-area">
        <input type="search-text" name= "area" id="search-input" list="areas" placeholder="Pick your date area..." autofocus>
        <% Venue::AREAS.each do |area| %>
        <option value="<%= area %>"><% area %></option>
        <% end %>
      </div>

      <div class="venue-categories">
        <div class="venue-category">
          <%= render "shared/icons/restaurant" %>
          <h3>Restaurant</h3>
          <input name='restaurant' id="checkbox-restaurant" class="venue-checkbox" type="checkbox" />
        </div>
        <div class="venue-category checked">
          <%= render "shared/icons/bar" %>
          <h3>Bar</h3>
          <input name='bar' id="checkbox-bar" class="venue-checkbox" type="checkbox" checked="checked"/>
        </div>
        <div class="venue-category">
          <%= render "shared/icons/cafe" %>
          <h3>Cafe</h3>
          <input name='cafe' id="checkbox-cafe" class="venue-checkbox" type="checkbox" />
        </div>
      </div>

      <div class="btn-center">
        <button type="submit" value="" class="next-page-button">
          <i class="fa fa-chevron-circle-right" aria-hidden="true"></i><p class="next-page">Next</p>
        </button>
      </div>
    </form>
  </div>
</div>

app/views/pages/moodselector.html.erb
<h1 class="text-center">What kind of magical mood do you want?</h1>

<div class="moods">
  <% moods = ['fun', 'chill', 'seductive', 'adventurous', 'classy', 'random'] %>
  <div class="row">
  <% moods.each do |mood| %>
  <div class="col-xs-12 col-md-4 not-padded">
    <%= link_to venues_path(mood: mood, bar: params[:bar], restaurant: params[:restaurant], cafe: params[:cafe], area: params[:area]) do %>
    <div class="<%= mood %>-filter">
      <%= image_tag "#{mood}.jpg", class: 'mood' %>
    </div>
    <% end %>
    <h3 class="mood-name"><%= mood.capitalize %></h3>
  </div>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar-home.html.erb
<div class="navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "unicorn-white.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <% avatar_url = current_user.facebook_picture_url || current_user.photo %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
        </li>
        <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
        </li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="unicorn-navbar <%= content_for?(:navbar_class) ? yield(:navbar_class) : '' %>">
  <%= link_to root_path do %>
    <% if content_for?(:navbar_class) %>
      <%= image_tag "logo-peach.png", id: "logo" %>
    <% else %>
      <%= image_tag "logo-peach-dark.png", id: "logo" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <div class="nav-corner-right">
      <% if current_user.admin %>
        <%= link_to 'Create Venue', new_venue_path %>
      <% end %>
      <p style="margin: 0;"><%= current_user.first_name %>    <strong><%= current_user.point %> pts</strong></p>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      <%= link_to dashboard_path, class: "dashboard-link" do %>
        <%= cl_image_tag current_user.unicorn.photo.path, id: "navbar-wagon-menu" %>
      <% end %>
    </div>

  <% else %>
    <%= link_to new_user_session_path do %>
      Log in
    <% end %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<h2 class="site-title">Shiny Unicorn // London, UK</h2>

<div class="social-btns">
  <a href="https://www.facebook.com" target="_blank">
    <i class="fa fa-facebook" aria-hidden="true" ></i>
  </a>
  <a href="https://www.instagram.com" target="_blank">
    <i class="fa fa-instagram" aria-hidden="true"></i>
  </a>
  <a href="mailto:info@shinyunicorn.co" target="_blank">
    <i class="fa fa-envelope" aria-hidden="true"></i></i>
  </a>
</div>

app/views/shared/icons/_bar.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<svg width="500px" height="500px" viewBox="0 0 500 500" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="assymetrical">
    <!-- Generator: Sketch 42 (36781) - http://www.bohemiancoding.com/sketch -->
    <title>cocktails</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="cocktails" transform="translate(-1.000000, 0.000000)" fill-rule="nonzero" fill="#000000">
            <g id="Layer_1">
                <path d="M387.34082,0 C332.463867,0 286.548828,39.1035156 275.991211,90.9091797 L23.7041016,90.9091797 C14.5097656,90.9091797 6.22265625,96.4482422 2.70507812,104.942383 C-0.811523438,113.436523 1.13574219,123.213867 7.63867188,129.711914 L182.794922,304.766602 L182.794922,454.544922 L114.560547,454.544922 C102.008789,454.544922 91.8330078,464.720703 91.8330078,477.272461 C91.8330078,489.824219 102.008789,500 114.560547,500 L296.484375,500 C309.036133,500 319.211914,489.824219 319.211914,477.272461 C319.211914,464.720703 309.036133,454.544922 296.484375,454.544922 L228.25,454.544922 L228.25,304.766602 L324.634766,208.439453 C343.072266,220.689453 364.700195,227.272461 387.34082,227.272461 C450,227.272461 500.976562,176.295898 500.976562,113.636719 C500.976562,50.9775391 450,0 387.34082,0 Z M205.522461,263.216797 L78.5947266,136.364258 L332.449219,136.364258 L205.522461,263.216797 Z M387.34082,181.818359 C376.986328,181.818359 366.988281,179.518555 357.917969,175.174805 L403.407227,129.712891 C409.910156,123.212891 411.857422,113.4375 408.338867,104.943359 C404.822266,96.4492187 396.53418,90.9101562 387.339844,90.9101562 L323.067383,90.9101562 C332.449219,64.4589844 357.710938,45.4560547 387.339844,45.4560547 C424.935547,45.4560547 455.521484,76.0419922 455.521484,113.637695 C455.521484,151.233398 424.935547,181.818359 387.34082,181.818359 Z" id="Shape"></path>
            </g>
        </g>
    </g>
</svg>

app/views/shared/icons/_cafe.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<svg width="527px" height="500px" viewBox="0 0 527 500" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="assymetrical">
    <!-- Generator: Sketch 42 (36781) - http://www.bohemiancoding.com/sketch -->
    <title>coffee-cup</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="coffee-cup" fill-rule="nonzero" fill="#000000">
            <g id="Capa_1">
                <g id="Group">
                    <path d="M458.062807,265.003752 L421.689536,265.003752 L423.611111,224.657624 C423.828648,220.085137 422.163655,215.621453 419.006582,212.309957 C415.849509,208.998461 411.470884,207.123713 406.897033,207.123713 L38.7773315,207.123713 C34.2006917,207.123713 29.824855,208.998461 26.6677822,212.309957 C23.5107095,215.624242 21.8457162,220.085137 22.063253,224.657624 L29.4929719,380.562963 C31.3280901,419.090139 54.9196787,451.507648 88.0661535,466.235017 L16.7336011,466.235017 C7.49386435,466.235017 0,473.731217 0,482.973834 C0,492.21645 7.49386435,499.71265 16.7336011,499.71265 L431.300201,499.71265 C440.539938,499.71265 448.033802,492.21645 448.033802,482.973834 C448.033802,473.731217 440.539938,466.235017 431.300201,466.235017 L357.611,466.235017 C384.479585,454.294661 405.050759,430.729197 412.859772,401.704089 L458.062807,401.704089 C495.73851,401.704089 526.391678,371.041366 526.391678,333.35392 C526.391678,295.666474 495.73851,265.003752 458.062807,265.003752 Z M317.439201,441.266282 L128.237952,441.266282 C93.2758813,441.266282 64.5861223,413.901106 62.921129,378.967196 L56.3280901,240.595767 L389.346274,240.595767 L382.756024,378.967196 C381.091031,413.901106 352.401272,441.266282 317.439201,441.266282 Z M458.062807,368.226455 L416.772646,368.226455 L420.097055,298.445118 C420.34527,298.456277 420.590696,298.481385 420.8417,298.481385 L458.062807,298.481385 C477.286925,298.481385 492.924476,314.12381 492.924476,333.35392 C492.924476,352.584031 477.286925,368.226455 458.062807,368.226455 Z" id="Shape"></path>
                    <path d="M173.66689,179.686003 C176.338688,181.265031 179.269857,182.018278 182.16477,182.018278 C187.887662,182.018278 193.46274,179.077826 196.586345,173.793939 C201.291276,165.834632 198.652945,155.570948 190.696118,150.86734 C181.392236,145.365849 174.960955,135.216546 173.053324,123.025108 C171.067604,110.331506 174.383646,97.6881193 181.916555,89.2099086 C181.98349,89.1345839 182.050424,89.0592593 182.114569,88.9811448 C183.935743,86.8553151 185.756917,84.7657528 187.561357,82.6929293 C203.039938,64.9107263 219.048416,46.5287157 223.644578,19.774507 C225.211959,10.6630111 219.095828,2.00625301 209.98996,0.441173641 C200.881303,-1.12390572 192.227242,4.98855219 190.662651,14.1000481 C187.653391,31.6088504 175.91477,45.0919673 162.324297,60.7037037 C160.491968,62.807215 158.645694,64.9302549 156.79942,67.0839827 C142.768295,82.952381 136.484828,105.784127 139.990518,128.194613 C143.443217,150.30659 155.720103,169.073593 173.66689,179.686003 Z" id="Shape"></path>
                    <path d="M225.599621,141.886965 C231.124498,156.117749 240.980589,169.151708 253.355087,178.586821 C256.383869,180.896777 259.948126,182.015488 263.487282,182.015488 C268.529674,182.015488 273.516287,179.744589 276.807229,175.423184 C282.410196,168.072054 280.993418,157.568446 273.641789,151.963733 C266.212071,146.297643 260.070839,138.210005 256.796631,129.770851 C250.273315,112.967869 256.453592,96.2234728 277.465417,73.7795094 C292.361111,57.8664743 301.88253,39.1245791 304.997769,19.5736412 C306.450803,10.4454064 300.23427,1.86397306 291.106091,0.407696008 C281.980701,-1.04858105 273.401941,5.17267917 271.946118,14.3037037 C269.857207,27.412987 263.495649,39.7243867 253.037149,50.8975469 C242.062695,62.6175084 208.673583,98.2851371 225.599621,141.886965 Z" id="Shape"></path>
                </g>
            </g>
        </g>
    </g>
</svg>