config/routes.rb
Rails.application.routes.draw do

  # get 'dashboards/show'
  get "/dashboard", to: 'dashboards#show'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # get 'mood', to: 'pages#moodselector'
  # get "/dashboard", to: 'dashboards#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues, only: [:index, :new, :create, :show] do
    resources :favorites, only: :create
    resources :spots, only: :create
    resources :bookings, only: :create
    resources :reviews, only: :create
  end
  resources :favorites, only: [:destroy]
  resources :favorites, except: [:new, :create]

  mount Attachinary::Engine => "/attachinary"
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_attachment :photo
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :venue_categories, dependent: :destroy
  has_many :categories, through: :venue_categories
  has_many :spots, dependent: :destroy
  has_many :bookings, through: :spots

  CATEGORIES = ["Bar", "Restaurant", "Cafe"]
  MOODS = ['fun', 'chill', 'seductive', 'adventurous', 'classy',]
  AREAS = ["Chelsea", "Shoreditch", "Soho", "Knightsbridge", "Mayfair", "Marylebone", "Hampstead", "Kensington"]
  validates :area, presence: true

  def favorite?(user)
    user.venues.include? self
    #user.venues.include? @venue <- you're trying to access @venue so using self.
  end


  private
  def area_in_london
    self.areas + ', London, UK'
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @venues = policy_scope(Venue)
    @venues = Venue.all
    @venues = @venues.where(area: params[:area]) if !params[:area].blank?
    @venues = @venues.where(mood: params[:mood]) if !params[:mood].blank?
    # @venues = @venue.near('Shoreditch', 10)

    # @venues = @venues.where(category: params[:category]) if !params[:category].blank?

    cat_array = []
    cat_array << 'restaurant' if params['restaurant'] == 'on'
    cat_array << 'bar' if params['bar'] == 'on'
    cat_array << 'cafe' if params['cafe'] == 'on'

    # @venues = @venues.where(category: cat_array) if cat_array.any?

    @venues = @venues.joins(:categories).where(categories: {title: cat_array}) if cat_array.any?

    @venues = @venues.uniq

    session[:area] = params[:area]
    session[:categories] = cat_array

    @hash = Gmaps4rails.build_markers(@venues) do |venue, marker|
      marker.lat venue.latitude
      marker.lng venue.longitude
      marker.picture({
                  url: view_context.image_path('unicorn-index.png'),
                  width: 45,
                  height: 75
                 })
      marker.infowindow render_to_string(partial: "/venues/map_box", locals: { venue: venue })
      marker.json({ id: venue.id })
    end

    # @favorite = Favorite.new
    # @is_favorite = current_user.venues.include? @venue

  end


  def show
    @hash = Gmaps4rails.build_markers(@venue) do |venue, marker|
      marker.lat venue.latitude
      marker.lng venue.longitude
      marker.picture({
          url: view_context.image_path('unicorn-icon.svg'),
          width: 50,
          height: 50
          })
    end

    @spot = Spot.new

    @favorite = Favorite.new

    @booking = Booking.new

    @review = Review.new

    if user_signed_in?
    @is_favorite = @venue.favorite?(current_user)

    end
    #checking if current user's favorite venues array includes the venue he's visiting now(@venue)

  end

  def new
    @venue = Venue.new
    authorize @venue
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to venues_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @venue.update(venue_params)
      redirect_to venues_path
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_path
  end


  private

  def set_venue
    @venue = Venue.find(params[:id])
    authorize @venue
  end

  def venue_params
    params.require(:venue).permit(:name, :address, :area, :category, :mood, :description, :price, :light_level, :noise_level, :couch_comfort, :staff_level, :unicorn_score, :photo)
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="form-wrapper">


      <h1 class="text-center">Create New Venue</h1><br>


        <%= simple_form_for(@venue) do |f| %>
        <%= f.error_notification %>

        <%= f.input :name, as: :string %>

        <%= f.input :address, as: :string %>

        <%= f.input :area, collection: Venue::AREAS %>

        <%# f.input :category, collection: Category.all %>

        <%= f.input :mood, collection: Venue::MOODS %>

        <%= f.input :description, label:'Description' %>

        <%= f.input :price, collection: 1..3 %>

        <%= f.input :light_level, label:'0 being dark - 10 being bright',collection: 1..10 %>

        <%= f.input :noise_level, label:'0 being quiet - 10 being loud',collection: 1..10 %>

        <%= f.input :couch_comfort, label:'0 being stiff - 10 being very comfy', collection: 1..10 %>

        <%= f.input :staff_level, label:'0 being bad service - 10 being extremely good service', collection: 1..10 %>

        <%= f.input :unicorn_score, collection: 1..10 %>

        <%= f.submit "Create a venue", class: "shiny-btn" %>
        <br>
        <br>

        <button class="shiny-btn"><%= link_to 'Back', root_path %></button>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/venues/_map_box.html.erb
<div class="map_box">
  <div class="align-items">
    <h4 class="venue-title"><%= venue.name %></h4>

  </div>
  <h5 class="venue-mood3"><%= venue.mood.capitalize %></h5>
  <p><%= venue.address %></p>
  <p><%= venue.area.upcase %></p>

  <div class="stream-body-bars">
    <div class="img_progress">
      <div class="text-center" data-toggle="tooltip" data-placement="top" title="Hotness Level">
        <%= image_tag 'chili.svg', class:"img_format2" %>
      </div>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" style="width: 90%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
        </div>
      </div>
    </div>
  </div>
  <br>
    <%= link_to "Details", venue_path(venue), target: :blank, class: "btn btn-primary details-center" %>
</div>

app/views/venues/_venue_profile.html.erb
<div class="venue-profile">
  <h3 class="gold-title">Venue Details</h3>
  <hr>
  <p><i class="fa fa-map-marker logo-loca"></i><span><strong>Address: </strong></span></p>
  <p class="ven-add "><%= @venue.address %>, <%= @venue.area %>, London </p>
  <p><strong>Price: </strong><%= '£  ' * @venue.price %></p>
  <p><strong>Area: </strong><%= @venue.area %></p>
  <!-- <div class="divider2"></div> -->
  <p class=""><strong>Description: </strong><%= @venue.description %></p>
  <div class="divider2"></div>

  <div class="stream-body-bars">
    <div class="img_progress">
    <div class="text-center" data-toggle="tooltip" data-placement="top" title="Hotness Level">
      <%= image_tag 'chili.svg', class:"img_format2" %>
    </div>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" style="width: <%= @venue.unicorn_score * 10 %>%" aria-valuenow="<%= @venue.unicorn_score * 10 %>" aria-valuemin="0" aria-valuemax="100">
        </div>
      </div><span class="venue-score"><%= @venue.unicorn_score %>/10</span>
    </div>
    <div class="img_progress">
    <div class="text-center" data-toggle="tooltip" data-placement="top" title="Couch Comfortness Level">
      <%= image_tag 'sofa.svg', class:"img_format2" %>
    </div>
      <div class="progress">
        <div class="progress-bar progress-bar-danger" role="progressbar" style="width: <%= @venue.couch_comfort * 10 %>%" aria-valuenow="<%= @venue.couch_comfort * 10 %>" aria-valuemin="0" aria-valuemax="100">
        </div>
      </div><span class="venue-score"><%= @venue.couch_comfort %>/10</span>
    </div>
    <div class="img_progress">
    <div class="text-center" data-toggle="tooltip" data-placement="top" title="Noise Level">
      <%= image_tag 'noise.svg', class:"img_format2" %>
    </div>
      <div class="progress">
        <div class="progress-bar progress-bar-warning" role="progressbar" style="width: <%= @venue.noise_level * 10 %>%" aria-valuenow="<%= @venue.noise_level * 10 %>" aria-valuemin="0" aria-valuemax="100">
        </div>
      </div><span class="venue-score"><%= @venue.noise_level %>/10</span>
    </div>
  </div>
</div>

app/views/venues/_venue_spots.html.erb
<div class="venue-spots">
  <h3 class="gold-title">Hot Spots</h3>
  <hr>

  <% unless @venue.spots.empty? %>
  <div class="venue-spot-photos">
    <% @venue.spots.each do |spot| %>
      <% if spot.photo %>
        <%= link_to cl_image_path(spot.photo.path) do %>
          <%= cl_image_tag(spot.photo.path, crop: :thumb, width: 200, height: 200) %>
          <span><%= spot.name || "test" %></span>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <% end %>
  <br>

  <% if user_signed_in? %>
  <button type="" value="Add a Spot to this Venue" class="btn shiny-btn2" id="create-spot">
  Create Spot</button>
  <%= render 'spots/spot-form' if user_signed_in? %>
  <% else %>
  <%= link_to "Create Spot", new_user_session_path, class: "btn shiny-btn2" %>
  <% end %>
</div>

app/views/venues/_venuecard.html.erb
<div class="col-xs-12 col-md-4">
  <div class="stream-entry-inner" >
    <%=  link_to venue_path(venue) do %>
    <div class="stream-image" style="background-image: url(<%= cl_image_path venue.photo.path%>)">
      <div class="venue-mood2">
        <p><%= venue.mood.capitalize %></p>
      </div>
      <div class="card_description">
        <h4><%= venue.name %></h4>
      </div>

    </div>

    <% end %>
    <div class="border-bc">
      <div class="stream-body">
        <div class="stream-body-description">
          <p><%= truncate(venue.description, length: 100, separator: ' ') %></p>
        </div>
        <div class="stream-body-bars">
          <div class="img_progress">
            <div class="text-center" data-toggle="tooltip" data-placement="top" title="Hotness Level">
              <%= image_tag 'chili.svg', class:"img_format2" %>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-success" role="progressbar" style="width: 90%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
              </div>
            </div>
          </div>
          <div class="img_progress">
            <div class="text-center" data-toggle="tooltip" data-placement="top" title="Couch Comfortness Level">
              <%= image_tag 'sofa.svg', class:"img_format2" %>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-danger" role="progressbar" style="width: 55%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
              </div>
            </div>
          </div>
          <div class="img_progress">
            <div class="text-center" data-toggle="tooltip" data-placement="top" title="Noise Level">
              <%= image_tag 'noise.svg', class:"img_format2" %>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="stream-body2">
        <a href="#"><i class="fa fa-instagram"></i></a>
        <span><%= venue.area %>  | <%= '£' * venue.price %></span>


        <% if venue.favorite?(current_user) %>
            <%= link_to favorite_path(venue.favorites.find_by_user_id(current_user.id)), method: :delete do %>
              <i class="fa fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to venue_favorites_path(venue), method: :post do %>
            <i class="fa fa-heart-o"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/create.html.erb
<h1>Venues#create</h1>
<p>Find me in app/views/venues/create.html.erb</p>

app/views/venues/destroy.html.erb
<h1>Venues#destroy</h1>
<p>Find me in app/views/venues/destroy.html.erb</p>

app/views/venues/edit.html.erb
<div class="wrapper-login">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 ">
        <h3>Edit Venue</h3>

        <%= simple_form_for @venue do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, as: :string %>

        <%= f.input :address, as: :string %>

        <%= f.input :area, collection: Venue::AREAS %>

        <%= f.input :category, collection: Venue::CATEGORIES %>

        <%= f.input :mood, collection: Venue::MOODS %>

        <%= f.input :description, label:'Description', %>

        <%= f.input :price %>

        <%= f.input :light_level, label:'0 being dark - 10 being bright', as: :integer %>

        <%= f.input :noise_level, label:'0 being quiet - 10 being loud', as: :integer %>

        <%= f.input :couch_comfort, label:'0 being stiff - 10 being very comfy', as: :integer %>

        <%= f.input :staff_level, label:'0 being bad service - 10 being extremely good service', as: :integer %>

        <%= f.input :unicorn_score, as: :string %>

        <%= f.button :submit, class:"submit-btn" %>

        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>

        <%= link_to "Delete venue", venue_path(@venue), method: :delete %> |
        <%= link_to "Back Home", root_path %>

      </div>
    </div>
  </div>
</div>

app/views/venues/index.html.erb
<div class="venues-wrapper">
  <div class="results">
    <div class="filter">
      <div class="container-fluid">
        <h2><strong>What Kind of Magical Mood Do You Want?</strong></h2>
        <form action="" class="form-inline">
          <input type="hidden" name="area" value="<%=params[:area]%>">
          <% if params[:restaurant] %>
            <input type="hidden" name="restaurant" value="<%=params[:restaurant]%>">
          <% end %>
          <% if params[:bar] %>
            <input type="hidden" name="bar" value="<%=params[:bar]%>">
          <% end  %>
          <% if params[:cafe] %>
            <input type="hidden" name="cafe" value="<%=params[:cafe]%>">
          <% end  %>

          <% Venue::MOODS.each do |mood| %>
            <% if params[:mood] && params[:mood].include?(mood) %>
              <label for="<%= mood %>" class="mood-choice active">
                <input type="checkbox" name="mood[]" value="<%= mood %>" id="<%= mood %>" checked class="hidden">
                <%= mood.capitalize %> <i class="fa fa-check"></i>
              </label>
            <% else %>
              <label for="<%= mood %>" class="mood-choice">
                <input type="checkbox" name="mood[]" value="<%= mood %>" id="<%= mood %>" class="hidden">
                <%= mood.capitalize %> <i class="fa fa-check"></i>
              </label>
            <% end %>
          <% end %>


          <button type="submit" class="btn btn-danger" style="padding: 10px;">Apply</button>
        </form>
      </div>
    </div>
    <div class="container-fluid results-list">
      <div class="row">
        <% @venues.each_with_index do |venue, index| %>
          <div class="col-xs-12 col-md-6" id="venue-<%= venue.id %>">
            <div class="stream-entry-inner" >
              <%=  link_to venue_path(venue) do %>
              <div class="stream-image" style="background-image: url(<%= cl_image_path venue.photo.path %>)">
                <div class="venue-mood2">
                <p><%= venue.mood.capitalize %></p>
                </div>
                <div class="card_description">
                    <h4><%= venue.name %></h4>
                  </div>
                </div>
              <% end %>
              <div class="border-bc">
                <div class="stream-body">
                  <div class="stream-body-description">
                    <p><%= truncate(venue.description, length: 100, separator: ' ') %></p>
                  </div>
                  <div class="stream-body-bars">
                    <div class="img_progress">
                    <div class="text-center" data-toggle="tooltip" data-placement="top" title="Hotness Level">
                      <%= image_tag 'chili.svg', class:"img_format2" %>
                    </div>
                      <div class="progress">
                        <div class="progress-bar progress-bar-success" role="progressbar" style="width: <%= venue.unicorn_score * 10 %>%" aria-valuenow="<%= venue.unicorn_score * 10 %>" aria-valuemin="0" aria-valuemax="100">
                        </div>
                      </div>
                        <span class="venue-score"><%= venue.unicorn_score %>/10</span>
                    </div>
                    <div class="img_progress">
                    <div class="text-center" data-toggle="tooltip" data-placement="top" title="Couch Comfortness Level">
                      <%= image_tag 'sofa.svg', class:"img_format2" %>
                    </div>
                      <div class="progress">
                        <div class="progress-bar progress-bar-danger" role="progressbar" style="width: <%= venue.couch_comfort * 10 %>%" aria-valuenow="<%= venue.couch_comfort * 10 %>" aria-valuemin="0" aria-valuemax="100">
                        </div>
                      </div>
                        <span class="venue-score"><%= venue.couch_comfort %>/10</span>
                    </div>
                    <div class="img_progress">
                    <div class="text-center" data-toggle="tooltip" data-placement="top" title="Noise Level">
                      <%= image_tag 'noise.svg', class:"img_format2" %>
                    </div>
                      <div class="progress">
                        <div class="progress-bar progress-bar-warning" role="progressbar" style="width: <%= venue.noise_level * 10 %>%" aria-valuenow="<%= venue.noise_level * 10 %>" aria-valuemin="0" aria-valuemax="100">
                        </div>
                      </div>
                      <span class="venue-score"><%= venue.noise_level %>/10</span>
                    </div>
                  </div>
                </div>
                <div class="stream-body2">
                  <a href="#"><i class="fa fa-instagram"></i></a>


                  <span><%= venue.area %>  | <%= '£' * venue.price %></span>


                  <% if user_signed_in? && venue.favorite?(current_user) %>
                    <%= link_to favorite_path(venue.favorites.find_by_user_id(current_user.id)), method: :delete do %>
                    <i class="fa fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= link_to venue_favorites_path(venue), method: :post do %>
                    <i class="fa fa-heart-o"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="map" style="width: 100%; height: 100vh-60px;"></div>
</div>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {


      markers_json = <%=raw @hash.to_json %>;
      markers = _.map(markers_json, function(marker_json){
        marker = handler.addMarker(marker_json);
        _.extend(marker, marker_json);
        return marker;
      });

    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();

      for (var i = 0; i <  markers.length; ++i) {
        var marker = markers[i];
        google.maps.event.addListener(marker.serviceObject, 'click', scrollToVenue(marker, event));
      }

      function scrollToVenue(marker, event){
        return function(event){
          var venue = '#venue-' + marker.id;
          document.querySelector(venue).scrollIntoView({ behavior: 'smooth' });
          $('.stream-entry-inner').removeClass('border-gold');
          $(venue + ' .stream-entry-inner').addClass('border-gold');

        }
      }

      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  });
</script>
<% end %>

app/views/venues/new.html.erb
<%= render 'form', venue: @venue %>

app/views/venues/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.20) 50%), url('<%= cl_image_path @venue.photo.path %>');">
  <div class="banner-text">
    <div class="venue-mood">
      <p><%= @venue.mood.capitalize %></p>
    </div>
    <div class='venue-name'>
      <h1><%= @venue.name.upcase %></h1>
    </div>
  </div>
</div>

<div class="sub-banner">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <div class="fav-loc">
          <% if @is_favorite %>
          <%= link_to favorite_path(@venue.favorites.find_by_user_id(current_user.id)), method: :delete do %>
          <i class="fa fa-heart"></i> <span class="extra-padding">Remove from Favorites</span>
          <% end  %>
          <% else %>
          <%= link_to venue_favorites_path(@venue), method: :post do %>
          <i class="fa fa-heart-o"></i> <span class="extra-padding">Add to Favorites</span>
          <% end %>
          <% end %>
        </div>
        <div class="fav-loc"><i class="fa fa-map-marker logo-loca"></i><span><%= @venue.area %> | <%= '£ ' * @venue.price %></span>
        </div>
        <div class='socialrow'>
      <%= link_to '#' do %>
      <div class='socialbutton instagram'>
        <i class="fa fa-instagram"></i>
      </div>
      <% end %>
      <%= link_to '#' do %>
      <div class='socialbutton facebook'>
        <i class="fa fa-facebook"></i>
      </div>

      <% end %>
      <%= link_to '#' do %>
      <div class='socialbutton twitter'>
        <i class="fa fa-twitter"></i>
      </div>
      <% end %>
    </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <button type="" value="Create a Spot in Venue" class="btn shiny-btn" id="create-spot-now">Book a Spot</button>
      </div>
    </div>
    <div class="sub-banner-content-booking">

    </div>
  </div>
</div>

<div class="description-box">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <%= render "venue_profile" %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="booking-form">
          <h3 class="gold-title">Book a Spot</h3>
          <%= simple_form_for [@venue, @booking] do |f| %>
            <%= f.association :spot, collection: @venue.spots, :label_method => lambda { |spot| spot.name }, prompt: "Select your spot" %>
            <%= f.input :date, as: :string, placeholder: "Select your date" %>
            <%= f.submit "Book", class: "btn shiny-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="spots-box">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <%= render "venue_spots" %>
      </div>
    </div>
  </div>
</div>




<div class="description-box" id="reviews">
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-sm-8">
        <h3 class="gold-title">Reviews</h3>

        <% @venue.reviews.each do |review| %>
          <div class="unicorn-review">
            <div id="unicorn-review-photo" class="text-center">
              <%= cl_image_tag review.user.unicorn.photo.path, width: "50px"%>
              <p><%= review.user.first_name.first %>.<%= review.user.last_name.first %></p>
            </div>
            <div class="unicorn-review-description">
              <p>
                <% review.hotness_level.times do %>
                  <i class="fa fa-star" style="color: orange;"></i>
                <% end %>
                <% (5 - review.hotness_level).times do %>
                  <i class="fa fa-star" style="color: #E5E5E5;"></i>
                <% end %>
              </p>
              <p>
                <%= review.description %>
              <p>
            </div>
          </div>
        <% end %>
        <hr>
        <%= render 'reviews/review-form' %>
      </div>
    </div>
  </div>
</div>

<div>
  <div id="map" style="width: 100%; height: 300px; padding: 0px;"></div>
</div>

<% content_for :after_js do %>
<script>

  $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' }, provider: {scrollwheel: false} }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });

    $('.venue-spot-photos').magnificPopup({
      delegate: 'a',
      type: 'image',
      tLoading: 'Loading image #%curr%...',
      gallery: {
        enabled: true,
        navigateByImgClick: true,
        preload: [0,1] // Will preload 0 - before current, and 1 after the current image
      },
    });

    $('input#booking_date').datetimepicker();



    // BOOKING FORM
    var elemTop = $(".booking-form").offset().top;
    // var elemLeft = $(".booking-form").position().left;
    var elemWidth = $(".booking-form").width() + 26
    var mapEnter = $("#reviews").offset().top - $(window).height();

    $( document ).scroll(function() {
      var currentScroll = $(window).scrollTop();

      console.log(currentScroll > 360)

      if (currentScroll > 650) {
        var elemTop = $(".booking-form").offset().top;
        console.log(elemTop)
        $(".booking-form").css({
          "position": "fixed",
          "top": elemTop - currentScroll,
          "width": elemWidth
        })
      } else {
        $(".booking-form").css({
          "position": "static"
        })
      }
    });
    // BOOK NOW
    $("#create-spot-now").click(function() {
        $('html, body').animate({
            scrollTop: mapEnter
        }, 1000);
    });

    // CREATE SPOT
    $('#create-spot').click(function() {
      $('#create-spot-form').toggle("slow", function() {
    // Animation complete.
      });
    })
  });

</script>
<% end %>

app/views/venues/update.html.erb
<h1>Venues#update</h1>
<p>Find me in app/views/venues/update.html.erb</p>